# Generated by Django 4.1.2 on 2022-11-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="district",
            field=models.CharField(max_length=50),
        ),
    ]
