# Generated by Django 4.1.2 on 2022-11-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0002_alter_address_district"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="city",
            field=models.CharField(default="Arcoverde", max_length=50),
            preserve_default=False,
        ),
    ]
