# Generated by Django 4.1.2 on 2022-11-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="soft_delete",
            field=models.BooleanField(default=False),
        ),
    ]
