# Generated by Django 4.1.2 on 2022-11-03 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_employee_soft_delete"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="soft_delete",
        ),
    ]
