# Generated by Django 4.1.2 on 2022-11-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_pregnant", models.BooleanField()),
                ("is_diabetic", models.BooleanField()),
                ("is_smoker", models.BooleanField()),
                ("is_allergic", models.BooleanField()),
                ("heart_disease", models.BooleanField()),
                ("dificulty_healing", models.BooleanField()),
                ("use_medication", models.BooleanField()),
                ("other_information", models.TextField()),
            ],
        ),
    ]
