# Generated by Django 4.1.2 on 2022-11-04 17:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        ("specialties", "0001_initial"),
        ("medics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "start_at",
                    models.DateTimeField(
                        default=datetime.datetime(2022, 11, 4, 14, 49, 21, 198253)
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("step", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "medic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Schedules",
                        to="medics.medic",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Schedules",
                        to="patients.patient",
                    ),
                ),
                (
                    "specialty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patients",
                        to="specialties.specialty",
                    ),
                ),
            ],
        ),
    ]
