# Generated by Django 4.1.3 on 2022-11-07 00:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="start_at",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 6, 21, 22, 1, 193475)
            ),
        ),
    ]
