# Generated by Django 4.1.2 on 2022-11-04 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="start_at",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 4, 16, 6, 13, 187927)
            ),
        ),
    ]
