# Generated by Django 4.1.2 on 2022-11-08 00:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="start_at",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 7, 21, 31, 25, 334847)
            ),
        ),
    ]
