# Generated by Django 4.1.2 on 2022-11-04 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0002_alter_schedule_start_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="start_at",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 4, 12, 52, 8, 55761)
            ),
        ),
    ]
