# Generated by Django 4.1.3 on 2022-11-05 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0004_alter_schedule_start_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="start_at",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 5, 15, 23, 39, 942438)
            ),
        ),
    ]
